# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: PullRequest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: false

    - name: Setup dotnetCore environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: |
        dotnet build --configuration debug DataverseClient.csproj

    - name: Run
      run: |
        dotnet run --no-build --configuration debug https://ppdevtools.crm.dynamics.com 8a7729e0-2b71-4919-a89a-c789d0a9720a "${{ secrets.PP_BT_ENV_SECRET }}"
