# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: PullRequest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: false

    - name: Setup dotnetCore environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build
      run: |
        dotnet build --configuration debug DataverseClient.csproj

    - name: Run
      run: |
        dotnet run --no-build --configuration debug DataverseClient.csproj -- https://davidjenD365-1.crm.dynamics.com
        2c6d7c95-ff20-4305-b87c-b97eb8277cf5 "${{ secrets.PP_BT_ENV_SECRET }}"
